In [1]:
height=[4.2,5.2,5.6,5.8,6.2]
height


[4.2, 5.2, 5.6, 5.8, 6.2]

In [2]:
weight=[40,50,60,70,80]
weight

[40, 50, 60, 70, 80]

Numpay - Numeric Python


In [3]:
import numpy as np

In [4]:
np_height=np.array([4.2,5.2,5.6,5.8,6.2])
np_height

array([4.2, 5.2, 5.6, 5.8, 6.2])

In [5]:
np_weight=np.array([40,50,60,70,80])
np_height

array([4.2, 5.2, 5.6, 5.8, 6.2])

In [6]:
#BMI
np_bmi=np_weight/np_height**2
np_bmi

array([2.2675737 , 1.84911243, 1.91326531, 2.08085612, 2.08116545])

1D Array


In [7]:
arr1=np.array([1,2,3,4,5])
arr1.ndim

1

In [8]:
np.array([1,2.3,"hello",False]) # Numpy only allows one data type

array(['1', '2.3', 'hello', 'False'], dtype='<U32')

Python List


In [9]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list1+list2 # list concatenation

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Numpy Array

In [10]:
np_list1=np.array([1,2,3,4,5])
np_list2=np.array([6,7,8,9,10])
np_list1+np_list2 # Numpy array addition

array([ 7,  9, 11, 13, 15])

Numpy Subsetting

In [11]:
np_list2[2]

8

In [12]:
np_list2 > 6

array([False,  True,  True,  True,  True])

In [13]:
np_list2[np_list2 > 6] # Boolean indexing

array([ 7,  8,  9, 10])

2D Array


In [14]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
arr_2d # 2D array same number of rows and columns
# arr_2d.ndim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arr_2d[1,0] # 2nd row, 1st column

4

In [16]:
#To get last two matrices
arr_2d[1:] 

array([[4, 5, 6],
       [7, 8, 9]])

3D Array


In [17]:
arr_3d=np.array([
    [[1, 2, 3],[4, 5, 6]],
    [[7, 8, 9],[10, 11, 12]]
])

arr_3d.ndim # 3D array

3

In [18]:
arr_3d[1,1,2] 

12

Numpy Properties


In [19]:
np_list1=np.array([1,2,3,4,5])
np_list2=np.array([6,7,8,9,10])

np_list1.shape
np_list1.size
np_list1.dtype #search more properties

dtype('int32')

Bulitin Creation Method


In [ ]:
np.zeros((2,3)) # Create an array of zeros with shape (2,3) this is null vector
np.ones((2,3)) # Create an array of ones with shape (2,3) this is unit vector

array([[1., 1., 1.],
       [1., 1., 1.]])

Statistics


In [23]:
np.mean(np_list1) # Mean of the array

3.0

In [24]:
np.median(np_list2)

8.0

In [25]:
np.std(np_list2) # Standard deviation
np.var(np_list2) # Variance

2.0