In [2]:
height=[4.2,5.2,5.6,5.8,6.2]
height


[4.2, 5.2, 5.6, 5.8, 6.2]

In [3]:
weight=[40,50,60,70,80]
weight

[40, 50, 60, 70, 80]

Numpay - Numeric Python


In [5]:
import numpy as np

In [8]:
np_height=np.array([4.2,5.2,5.6,5.8,6.2])
np_height

array([4.2, 5.2, 5.6, 5.8, 6.2])

In [7]:
np_weight=np.array([40,50,60,70,80])
np_height

array([4.2, 5.2, 5.6, 5.8, 6.2])

In [9]:
#BMI
np_bmi=np_weight/np_height**2
np_bmi

array([2.2675737 , 1.84911243, 1.91326531, 2.08085612, 2.08116545])

1D Array


In [10]:
arr1=np.array([1,2,3,4,5])
arr1.ndim

1

In [ ]:
np.array([1,2.3,"hello",False]) # Numpy only allows one data type

array(['1', '2.3', 'hello', 'False'], dtype='<U32')

Python List


In [ ]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
list1+list2 # list concatenation

Numpy Array

In [12]:
np_list1=np.array([1,2,3,4,5])
np_list2=np.array([6,7,8,9,10])
np_list1+np_list2 # Numpy array addition

array([ 7,  9, 11, 13, 15])

Numpy Subsetting

In [13]:
np_list2[2]

8

In [14]:
np_list2 > 6

array([False,  True,  True,  True,  True])

In [15]:
np_list2[np_list2 > 6] # Boolean indexing

array([ 7,  8,  9, 10])

2D Array


In [19]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
arr_2d # 2D array same number of rows and columns
# arr_2d.ndim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr_2d[1,0] # 2nd row, 1st column

4

In [21]:
#To get last two matrices
arr_2d[1:] 

array([[4, 5, 6],
       [7, 8, 9]])

3D Array


In [26]:
arr_3d=np.array([
    [[1, 2, 3],[4, 5, 6]],
    [[7, 8, 9],[10, 11, 12]]
])

arr_3d.ndim # 3D array

3

In [ ]:
arr_3d[1,1,2] 

12

Numpy Properties


In [ ]:
np_list1=np.array([1,2,3,4,5])
np_list2=np.array([6,7,8,9,10])

np_list1.shape
np_list1.size
np_list1.dtype #search more properties

dtype('int32')